#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

x setup
x mon
x bg "${XDG_PICTURES_DIR:-$HOME/Pictures}/wp/one/progress.jpg" "${XDG_PICTURES_DIR:-$HOME/Pictures}/wp/one/lilies.jpg"
setxkbmap -layout us -variant colemak &
pgrep -u "$USER" -f clipmenud >/dev/null || clipmenud &
# dwmblocks &
# dwm
spectrwm
